name: CI
on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 16 * * *"

jobs:
  check:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear older runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list -L400 --json databaseId -q '.[].databaseId' | tail -n+10 | xargs -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE || :

      - name: Generate JSON
        run: |
          r=$(curl -Ls https://api.github.com/repos/MorpheApp/morphe-patches/releases/latest) || exit 1

          name=$(echo -E "$r" | jq -r '.assets | .[0] | .name')
          version_name="${name%.*}"

          if [ "$version_name" = "$(cat docs/version)" ]; then exit 0; fi
          echo -n "$version_name" >docs/version

          dl_url=$(echo -E "$r" | jq -r '.assets | .[0] | .browser_download_url')
          #wget "$dl_url" -O "$name"

          #java -jar patches-json-gen.jar "$name" "static/patches.json"

          tag_name=$(echo -E "$r" | jq -r '.tag_name')
          patches_dl_url="https://raw.githubusercontent.com/MorpheApp/morphe-patches/refs/tags/$tag_name/patches-list.json"
          wget "$patches_dl_url" -O "${version_name}.json"

          cat "${version_name}.json" | jq '.patches | map(select(.compatiblePackages."com.google.android.youtube" or .compatiblePackages == null))' >static/patches.json

      - name: patches
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: workers
          file_pattern: static/patches.json docs/version
          commit_message: Update patches.json
